require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VisitBlocksController do

  # This should return the minimal set of attributes required to create a valid
  # VisitBlock. As you add validations to VisitBlock, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "visit_type" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VisitBlocksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all visit_blocks as @visit_blocks" do
      visit_block = VisitBlock.create! valid_attributes
      get :index, {}, valid_session
      assigns(:visit_blocks).should eq([visit_block])
    end
  end

  describe "GET show" do
    it "assigns the requested visit_block as @visit_block" do
      visit_block = VisitBlock.create! valid_attributes
      get :show, {:id => visit_block.to_param}, valid_session
      assigns(:visit_block).should eq(visit_block)
    end
  end

  describe "GET new" do
    it "assigns a new visit_block as @visit_block" do
      get :new, {}, valid_session
      assigns(:visit_block).should be_a_new(VisitBlock)
    end
  end

  describe "GET edit" do
    it "assigns the requested visit_block as @visit_block" do
      visit_block = VisitBlock.create! valid_attributes
      get :edit, {:id => visit_block.to_param}, valid_session
      assigns(:visit_block).should eq(visit_block)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VisitBlock" do
        expect {
          post :create, {:visit_block => valid_attributes}, valid_session
        }.to change(VisitBlock, :count).by(1)
      end

      it "assigns a newly created visit_block as @visit_block" do
        post :create, {:visit_block => valid_attributes}, valid_session
        assigns(:visit_block).should be_a(VisitBlock)
        assigns(:visit_block).should be_persisted
      end

      it "redirects to the created visit_block" do
        post :create, {:visit_block => valid_attributes}, valid_session
        response.should redirect_to(VisitBlock.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved visit_block as @visit_block" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitBlock.any_instance.stub(:save).and_return(false)
        post :create, {:visit_block => { "visit_type" => "invalid value" }}, valid_session
        assigns(:visit_block).should be_a_new(VisitBlock)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitBlock.any_instance.stub(:save).and_return(false)
        post :create, {:visit_block => { "visit_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested visit_block" do
        visit_block = VisitBlock.create! valid_attributes
        # Assuming there are no other visit_blocks in the database, this
        # specifies that the VisitBlock created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VisitBlock.any_instance.should_receive(:update_attributes).with({ "visit_type" => "MyString" })
        put :update, {:id => visit_block.to_param, :visit_block => { "visit_type" => "MyString" }}, valid_session
      end

      it "assigns the requested visit_block as @visit_block" do
        visit_block = VisitBlock.create! valid_attributes
        put :update, {:id => visit_block.to_param, :visit_block => valid_attributes}, valid_session
        assigns(:visit_block).should eq(visit_block)
      end

      it "redirects to the visit_block" do
        visit_block = VisitBlock.create! valid_attributes
        put :update, {:id => visit_block.to_param, :visit_block => valid_attributes}, valid_session
        response.should redirect_to(visit_block)
      end
    end

    describe "with invalid params" do
      it "assigns the visit_block as @visit_block" do
        visit_block = VisitBlock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitBlock.any_instance.stub(:save).and_return(false)
        put :update, {:id => visit_block.to_param, :visit_block => { "visit_type" => "invalid value" }}, valid_session
        assigns(:visit_block).should eq(visit_block)
      end

      it "re-renders the 'edit' template" do
        visit_block = VisitBlock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitBlock.any_instance.stub(:save).and_return(false)
        put :update, {:id => visit_block.to_param, :visit_block => { "visit_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested visit_block" do
      visit_block = VisitBlock.create! valid_attributes
      expect {
        delete :destroy, {:id => visit_block.to_param}, valid_session
      }.to change(VisitBlock, :count).by(-1)
    end

    it "redirects to the visit_blocks list" do
      visit_block = VisitBlock.create! valid_attributes
      delete :destroy, {:id => visit_block.to_param}, valid_session
      response.should redirect_to(visit_blocks_url)
    end
  end

end
